name: Build

on:
  push:
    branches: []
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make

      - uses: actions/upload-artifact@v3
        with:
          name: MoveNight
          path: MovieNight

      - uses: actions/upload-artifact@v3
        with:
          name: main.wasm
          path: static/main.wasm

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make

      - uses: actions/upload-artifact@v3
        with:
          name: MoveNight.exe
          path: MovieNight.exe

      - uses: actions/upload-artifact@v3
        with:
          name: main.wasm
          path: static/main.wasm
