name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: vet
        run: go vet

      - name: test
        run: go test

  build:
    runs-on: ubuntu-latest

    needs: pre-build

    strategy:
      matrix:
        target: [linux, windows, darwin]
        arch: [amd64, arm64]

    env:
      GOOS: ${{ matrix.target }}
      GOARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: build
        run: go build

      - uses: actions/upload-artifact@v3
        with:
          name: MovieNight-${{ matrix.target }}-${{ matrix.arch }}
          if-no-files-found: error
          path: MovieNight*
