name: Build

on:
  push:
    branches: []
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, windows]

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make

      - name: copy settings
        run: cp settings_example.json settings.json

      - uses: actions/upload-artifact@v3
        with:
          name: MoveNight-${{ matrix.os }}
          if-no-files-found: error
          path: |
            MovieNight
            static/
            settings.json

  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: build
  #       run: make

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: MoveNight-Windows
  #         if-no-files-found: error
  #         path: |
  #           MovieNight.exe
  #           static/
