name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [linux, windows, darwin]
        arch: [amd64, arm64]

    env:
      GOOS: ${{ matrix.target }}
      GOARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: test
        run: go test

      - name: build
        run: go build

      - name: create artifacts dir
        run: mkdir artifacts

      - name: copy settings
        run: cp settings_example.json artifacts/settings.json

      - name: copy static
        run: cp -r static artifacts/

      - name: copy MovieNight
        run: cp MovieNight* artifacts/

      - uses: actions/upload-artifact@v3
        with:
          name: MovieNight-${{ matrix.target }}-${{ matrix.arch }}
          if-no-files-found: error
          path: artifacts/*
