name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - artifact: MovieNight-Linux
            target: linux
            arch: amd64
          - artifact: MovieNight-Windows
            target: windows
            arch: amd64
          - artifact: MovieNight-Mac-x86_64
            target: darwin
            arch: amd64
          - artifact: MovieNight-Mac-ARM
            target: darwin
            arch: arm64

    env:
      GOOS: ${{ martix.target }}
      GOARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - name: vet
        run: go vet ./...

      - name: test
        run: go test ./...

      - name: build
        run: go build

      - name: copy settings
        run: cp settings_example.json settings.json

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          if-no-files-found: error
          path: |
            MovieNight*
            static/
            settings.json
