name: Build

on:
  push:
    branches: []
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make

      - name: build windows
        run: make TARGET=windows

      - uses: actions/upload-artifact@v3
        with:
          name: MoveNight
          path: MovieNight*

      - uses: actions/upload-artifact@v3
        with:
          name: main.wasm
          path: static/main.wasm
